Bot-Token: "TelegramBotToken"
Bot-Name: "KataraLSD"

Debug-Mode: false

# Seconds
Timer: 1800
Sleep-At:
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8

id-list:
  User: 1234567890
  User2: 13454567890
  User3: 12345678971